import '../styles/globals.scss'
import Layout from '@/components/layout'

export const metadata = {
  title: 'Portfolio Cédric Kuchen',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  )
}
